import { test, expect } from '@playwright/test';
test('project → editable AI draft → solver → review → confirmation',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await page.waitForLoadState('networkidle');
  await page.getByLabel('用户名',{exact:true}).fill('admin');
  await page.getByLabel('密码',{exact:true}).fill(process.env.ARO_ADMIN_PASSWORD!);
  await page.getByRole('button',{name:'进入工作台'}).click();
  await expect(page.getByRole('heading',{name:'把目标，变成团队的下一步。'})).toBeVisible();
  await page.screenshot({path:'../.temp/workspace.png',fullPage:true});
  await page.getByRole('button',{name:/团队成员/}).click();
  await expect(page.getByRole('heading',{name:'每一种能力，都被看见。'})).toBeVisible();
  if(await page.getByRole('button',{name:'载入 10 位演示员工'}).isVisible())await page.getByRole('button',{name:'载入 10 位演示员工'}).click();
  await expect(page.getByRole('button',{name:/陈知远/})).toBeVisible();
  await page.getByRole('button',{name:/陈知远/}).click();
  await expect(page.getByRole('heading',{name:'陈知远 · 能力画像'})).toBeVisible();
  await page.getByRole('button',{name:/项目与编排/}).click();
  await page.getByRole('button',{name:'新建项目',exact:true}).click();
  const name='浏览器闭环 '+Date.now();
  await page.getByLabel('项目名称').fill(name);
  await page.getByLabel('项目目标与交付要求').fill('建设团队能力平台，完成需求、开发和交付。');
  await page.getByLabel('开始日期').fill('2026-11-02');
  await page.getByLabel('结束日期').fill('2026-11-27');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await expect(page.getByRole('heading',{name,exact:true})).toBeVisible();
  await page.getByRole('button',{name:'生成演示规划',exact:true}).click();
  await expect(page.getByRole('heading',{name:'检查并完善规划'})).toBeVisible({timeout:85000});
  await page.getByRole('button',{name:'编辑',exact:true}).first().click();
  await page.getByLabel('任务名称').fill('确认需求范围');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.getByRole('button',{name:'确认导入任务'}).click();
  await expect(page.getByRole('button',{name:'确认需求范围',exact:true})).toBeVisible();
  await expect(page.locator('.gantt-bar').first()).toBeVisible();
  await page.getByRole('button',{name:'生成资源方案'}).click();
  await expect(page.getByText('无未分配任务',{exact:true})).toBeVisible({timeout:30000});
  await expect(page.getByText('跨项目负载预警（周占用 ≥80%）')).toBeVisible();
  await page.getByRole('button',{name:'查看演示解释'}).click();
  await expect(page.locator('.review')).toContainText('演示规则说明');
  await page.getByRole('button',{name:'确认并生效'}).click();
  await expect(page.getByText(/方案 v1 · 已确认生效/)).toBeVisible();
  await page.screenshot({path:'../.temp/confirmed-plan.png',fullPage:true});
  // Reload and re-open to prove the plan was persisted, not just changed in memory.
  await page.reload();await page.waitForLoadState('networkidle');
  await page.getByRole('button').filter({has:page.getByRole('heading',{name,exact:true})}).click();
  await page.getByLabel('选择资源方案').selectOption({label:'方案 v1 · CONFIRMED'});
  await expect(page.getByText(/已确认生效/)).toBeVisible();
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'../.temp/mobile.png',fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.setViewportSize({width:1280,height:900});
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'撤销方案',exact:true}).click();
  await expect(page.getByText(/方案 v1 · 已撤销/)).toBeVisible();
  expect(errors).toEqual([]);
});
test('gap analysis blocks confirmation and timeline renders weekly load',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await page.waitForLoadState('networkidle');
  await page.getByLabel('用户名',{exact:true}).fill('admin');
  await page.getByLabel('密码',{exact:true}).fill(process.env.ARO_ADMIN_PASSWORD!);
  await page.getByRole('button',{name:'进入工作台'}).click();
  await expect(page.getByRole('heading',{name:'把目标，变成团队的下一步。'})).toBeVisible();
  await page.getByRole('button',{name:'新建项目',exact:true}).click();
  const name='缺口场景 '+Date.now();
  await page.getByLabel('项目名称').fill(name);
  await page.getByLabel('项目目标与交付要求').fill('验证缺口分析与排期热力图。');
  await page.getByLabel('开始日期').fill('2026-11-02');
  await page.getByLabel('结束日期').fill('2026-11-06');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.getByRole('button',{name:'手动添加任务'}).click();
  await page.getByLabel('任务名称').fill('不可能完成的任务');
  await page.getByLabel('预计工时').fill('10000');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.getByRole('button',{name:'生成资源方案'}).click();
  await expect(page.getByText(/存在 1 项缺口/)).toBeVisible({timeout:30000});
  await expect(page.getByText('无满足技能和容量的候选员工')).toBeVisible();
  await expect(page.getByRole('button',{name:'确认并生效'})).toBeDisabled();
  await page.getByRole('button',{name:/团队成员/}).click();
  if(await page.getByRole('button',{name:'载入 10 位演示员工'}).isVisible())await page.getByRole('button',{name:'载入 10 位演示员工'}).click();
  await expect(page.getByRole('button',{name:/陈知远/}).first()).toBeVisible();
  await page.getByRole('button',{name:/资源排期/}).click();
  await expect(page.getByRole('heading',{name:'全员负荷，一览无余。'})).toBeVisible();
  await expect(page.locator('.timeline-table tbody')).toContainText('陈知远');
  await page.getByRole('button',{name:/团队成员/}).click();
  await page.getByRole('button',{name:/陈知远/}).click();
  await page.getByLabel('经历文本').fill('精通 Java，熟悉项目管理');
  await page.getByRole('button',{name:/识别技能/}).click();
  await expect(page.getByRole('heading',{name:/技能草稿/})).toBeVisible();
  await expect(page.locator('.draft-skills')).toContainText('Java');
  await page.getByRole('button',{name:/确认写入/}).click();
  await expect(page.locator('.skill-grid')).toContainText('Java');
  await page.locator('input[type=file]').setInputFiles({name:'resume.txt',mimeType:'text/plain',buffer:Buffer.from('精通 Java，参与 Spring Boot 服务开发')});
  await expect(page.getByRole('heading',{name:/技能草稿/})).toBeVisible();
  await expect(page.locator('.draft-skills')).toContainText('Java');
  await page.getByRole('button',{name:/组织与设置/}).click();
  await expect(page.getByRole('heading',{name:'集成通知'})).toBeVisible();
  expect(errors).toEqual([]);
});
test('leave conflict triggers impact analysis and atomic replan swap',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');await page.waitForLoadState('networkidle');
  await page.getByLabel('用户名',{exact:true}).fill('admin');
  await page.getByLabel('密码',{exact:true}).fill(process.env.ARO_ADMIN_PASSWORD!);
  await page.getByRole('button',{name:'进入工作台'}).click();
  await expect(page.getByRole('heading',{name:'把目标，变成团队的下一步。'})).toBeVisible();
  await page.getByRole('button',{name:'新建项目',exact:true}).click();
  const name='重规划 '+Date.now();
  await page.getByLabel('项目名称').fill(name);
  await page.getByLabel('项目目标与交付要求').fill('验证请假后的动态重规划闭环。');
  await page.getByLabel('开始日期').fill('2026-11-02');
  await page.getByLabel('结束日期').fill('2026-11-27');
  await page.getByRole('button',{name:'保存',exact:true}).click();
  await page.getByRole('button',{name:'生成演示规划',exact:true}).click();
  await expect(page.getByRole('heading',{name:'检查并完善规划'})).toBeVisible({timeout:85000});
  await page.getByRole('button',{name:'确认导入任务'}).click();
  await page.getByRole('button',{name:'生成资源方案'}).click();
  await expect(page.getByText('无未分配任务',{exact:true})).toBeVisible({timeout:30000});
  await page.getByRole('button',{name:'确认并生效'}).click();
  await expect(page.getByText(/方案 v1 · 已确认生效/)).toBeVisible();
  const employeeName=(await page.locator('table.plan-items tbody tr').first().locator('td').nth(1).textContent())!.trim();
  await page.getByRole('button',{name:/团队成员/}).click();
  await page.getByRole('button',{name:new RegExp(employeeName)}).first().click();
  await page.getByRole('button',{name:'+ 新增记录'}).click();
  await page.getByLabel('开始日期').fill('2026-11-01');
  await page.getByLabel('结束日期').fill('2026-11-30');
  await page.getByRole('combobox').last().selectOption('LEAVE');
  await page.getByRole('dialog').getByRole('button',{name:'保存',exact:true}).click();
  await page.getByRole('button',{name:/项目与编排/}).click();
  // 巡检横幅：品牌链接回项目列表，冲突项目可见 / patrol banner on the project list via the brand link
  await page.getByRole('link',{name:/ORCHESTRATOR/}).click();
  await expect(page.locator('.replan-alerts')).toContainText(name);
  await page.getByRole('button').filter({has:page.getByRole('heading',{name,exact:true})}).click();
  await page.getByLabel('选择资源方案').selectOption({label:'方案 v1 · CONFIRMED'});
  await page.getByRole('button',{name:'变更影响分析'}).click();
  await expect(page.locator('.impact-list')).toContainText('休假/不可用');
  await page.getByRole('button',{name:'重新求解（重规划）'}).click();
  await expect(page.getByText(/方案 v2 · 待人工确认/)).toBeVisible({timeout:30000});
  await expect(page.getByText('无未分配任务',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:/重规划差异说明/}).click();
  await expect(page.locator('.review')).toContainText('重规划');
  await page.getByRole('button',{name:'确认并生效'}).click();
  await expect(page.getByText(/方案 v2 · 已确认生效/)).toBeVisible();
  await expect(page.locator('.plan-banner').first()).not.toContainText('v1 · 已确认生效');
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'撤销方案',exact:true}).click();
  await expect(page.getByText(/方案 v2 · 已撤销/)).toBeVisible();
  // 自清理：删除为本测试添加的休假，避免占满后续运行的容量 / remove the leave this test created
  await page.getByRole('button',{name:/团队成员/}).click();
  await page.getByRole('button',{name:new RegExp(employeeName)}).first().click();
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'删除可用时间'}).click();
  await expect(page.getByText('暂无特殊安排，使用默认容量。')).toBeVisible();
  await page.getByRole('button',{name:/能力决策/}).click();
  await expect(page.getByRole('heading',{name:'看清组织的能力边界。'})).toBeVisible();
  await expect(page.locator('.sd-table tbody')).toContainText('Java');
  expect(errors).toEqual([]);
});
