-- Preserve V1; invalid legacy references must be repaired before upgrading.
ALTER TABLE department ADD FOREIGN KEY (parent_id) REFERENCES department(id);
ALTER TABLE employee ADD FOREIGN KEY (department_id) REFERENCES department(id);
ALTER TABLE sys_user ADD FOREIGN KEY (employee_id) REFERENCES employee(id);
ALTER TABLE skill ADD FOREIGN KEY (category_id) REFERENCES skill_category(id);
ALTER TABLE skill ADD FOREIGN KEY (parent_id) REFERENCES skill(id);
ALTER TABLE skill_alias ADD FOREIGN KEY (skill_id) REFERENCES skill(id) ON DELETE CASCADE;
ALTER TABLE employee_skill ADD FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE;
ALTER TABLE employee_skill ADD FOREIGN KEY (skill_id) REFERENCES skill(id);
ALTER TABLE employee_availability ADD FOREIGN KEY (employee_id) REFERENCES employee(id) ON DELETE CASCADE;
ALTER TABLE project ADD FOREIGN KEY (manager_id) REFERENCES employee(id);
ALTER TABLE project_milestone ADD FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE;
ALTER TABLE task ADD FOREIGN KEY (project_id) REFERENCES project(id) ON DELETE CASCADE;
ALTER TABLE task ADD FOREIGN KEY (parent_id) REFERENCES task(id);
ALTER TABLE task ADD FOREIGN KEY (milestone_id) REFERENCES project_milestone(id) ON DELETE SET NULL;
ALTER TABLE task_dependency ADD FOREIGN KEY (predecessor_task_id) REFERENCES task(id) ON DELETE CASCADE;
ALTER TABLE task_dependency ADD FOREIGN KEY (successor_task_id) REFERENCES task(id) ON DELETE CASCADE;
ALTER TABLE task_skill_requirement ADD FOREIGN KEY (task_id) REFERENCES task(id) ON DELETE CASCADE;
ALTER TABLE task_skill_requirement ADD FOREIGN KEY (skill_id) REFERENCES skill(id);
ALTER TABLE resource_plan ADD FOREIGN KEY (project_id) REFERENCES project(id);
ALTER TABLE resource_plan_item ADD FOREIGN KEY (plan_id) REFERENCES resource_plan(id) ON DELETE CASCADE;
ALTER TABLE resource_plan_item ADD FOREIGN KEY (project_id) REFERENCES project(id);
ALTER TABLE resource_plan_item ADD FOREIGN KEY (task_id) REFERENCES task(id);
ALTER TABLE resource_plan_item ADD FOREIGN KEY (employee_id) REFERENCES employee(id);
ALTER TABLE resource_allocation ADD FOREIGN KEY (project_id) REFERENCES project(id);
ALTER TABLE resource_allocation ADD FOREIGN KEY (task_id) REFERENCES task(id);
ALTER TABLE resource_allocation ADD FOREIGN KEY (employee_id) REFERENCES employee(id);
ALTER TABLE employee ADD CHECK (weekly_hours BETWEEN 1 AND 168);
ALTER TABLE task ADD CHECK (estimated_hours IS NULL OR estimated_hours >= 0);
ALTER TABLE resource_plan ADD COLUMN score_text VARCHAR(128);
ALTER TABLE resource_plan ADD COLUMN input_hash VARCHAR(64);
ALTER TABLE resource_plan ADD COLUMN gaps TEXT NOT NULL DEFAULT '[]';
ALTER TABLE resource_allocation ADD COLUMN plan_id BIGINT REFERENCES resource_plan(id);
CREATE UNIQUE INDEX uk_allocation_plan_task ON resource_allocation(plan_id,task_id);
