<script setup lang="ts">
import { reactive, ref } from 'vue';
export interface Field { key:string; label:string; type?:string; required?:boolean; options?:{value:any;label:string}[]; min?:number; max?:number; step?:number }
const props=defineProps<{title:string;fields:Field[];initial:Record<string,any>;save:(value:any)=>Promise<void>}>();
const emit=defineEmits<{close:[]}>();
const form=reactive({...props.initial}),busy=ref(false),error=ref('');
async function submit(){busy.value=true;error.value='';try{const value={...form}; for(const f of props.fields){if(value[f.key]==='')value[f.key]=null;else if(f.type==='number' && value[f.key]!=null)value[f.key]=Number(value[f.key]);}await props.save(value);emit('close');}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
</script>
<template><div class="overlay" @click.self="!busy&&emit('close')"><section class="dialog" role="dialog" aria-modal="true" :aria-label="title"><div class="dialog-head"><h2>{{title}}</h2><button class="icon-button" aria-label="关闭" :disabled="busy" @click="emit('close')">×</button></div><form @submit.prevent="submit"><div class="form-grid"><label v-for="f in fields" :key="f.key" :class="{'span-two':f.type==='textarea'}">{{f.label}} <span v-if="f.required">*</span><select v-if="f.type==='select'" v-model="form[f.key]" :required="f.required"><option :value="null">请选择</option><option v-for="o in f.options" :key="o.value" :value="o.value">{{o.label}}</option></select><textarea v-else-if="f.type==='textarea'" v-model="form[f.key]" :required="f.required" rows="4"></textarea><input v-else v-model="form[f.key]" :type="f.type||'text'" :required="f.required" :min="f.min" :max="f.max" :step="f.step" :autocomplete="f.type==='password'?'new-password':'off'"></label></div><p v-if="error" class="error" role="alert">{{error}}</p><div class="dialog-actions"><button type="button" class="secondary" :disabled="busy" @click="emit('close')">取消</button><button :disabled="busy">{{busy?'保存中…':'保存'}}</button></div></form></section></div></template>
